export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const VIEW_PROFILE = "VIEW_PROFILE";

export const ADD_APPLICANT = "ADD_APPLICANT";
export const GET_APPLICANTS = "GET_APPLICANTS";
export const VIEW_APPLICANT = "VIEW_APPLICANT";
export const VERIFY_APPLICANT = "VERIFY_APPLICANT"
export const FLAGGED_APPLICANTS = "FLAGGED_APPLICANTS"

export const GET_EMPLOYEES = "GET_EMPLOYEES";
