import React from 'react';
import LocalizedStrings from 'react-native-localization';

const setOfStrings = new LocalizedStrings({
  en: {
    login: 'Login',
    username: 'Username',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign Up',
    skip: 'Skip',
    submit: 'Submit',
    hey: 'Hey',
    overview: 'Overview',
    totalHoursWorked: 'Total Hours Worked',
    totaExperience: 'Total Experience',
    totalRedFlags: 'Total Red Flags',
    totalGreenFlags: 'Total Green Flags',
    jan: 'Jan',
    feb: 'Feb',
    mar: 'Mar',
    apr: 'Apr',
    may: 'May',
    jun: 'Jun',
    addImage: 'Add Image',
    recomSize: 'Recommended Size: 165px*65px',
    recentDetails: 'Recent Details',
  },
  hi: {
    login: 'लॉग इन करें',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    forgotPassword: 'पासवर्ड भूल गए?',
    resetPassword: 'पासवर्ड रीसेट करें',
    dontHaveAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    skip: 'छोड़ें',
    submit: 'प्रस्तुत करें',
    hey: 'हैलो',
    overview: 'अवलोकन',
    totalHoursWorked: 'कुल कार्य घंटे',
    totaExperience: 'कुल अनुभव',
    totalRedFlags: 'कुल लाल झंडे',
    totalGreenFlags: 'कुल हरा झंडा',
    jan: 'जनवरी',
    feb: 'फरवरी',
    mar: 'मार्च',
    apr: 'अप्रैल',
    may: 'मई',
    jun: 'जून',
    addImage: 'छवि जोड़ें',
    recomSize: 'अनुशंसित आकार: 165px * 65px',
    recentDetails: 'हाल की विवरण',
  },
  ma: {
    login: 'लॉग इन करें',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    forgotPassword: 'पासवर्ड भूल गए?',
    resetPassword: 'पासवर्ड रीसेट करें',
    dontHaveAccount: 'खाता नह ीं है?',
    signUp: 'साइन अप करें',
    skip: 'छोड़ें',
    submit: 'प्रस्तुत करें',
    hey: 'नमस्कार',
    overview: 'अवलोकन',
    totalHoursWorked: 'कुल कार्य घंटे',
    totaExperience: 'कुल अनुभव',
    totalRedFlags: 'कुल लाल झंडे',
    totalGreenFlags: 'कुल हरा झंडा',
    jan: 'जनवरी',
    feb: 'फरवरी',
    mar: 'मार्च',
    apr: 'अप्रैल',
    may: 'मई',
    jun: 'जून',
    addImage: 'छवि जोड़ें',
    recomSize: 'अनुशंसित आकार: 165px * 65px',
    recentDetails: 'हाल की विवरण',
  },
});

export default setOfStrings;
